### ISSUE TITLE
calling tomopy without paramenters

### ISSUE THREAD

**Issue by decarlof** [tomography/tomopy-cli#28]
throughs an error:
```
logs_home = args.logs_home
AttributeError: 'Namespace' object has no attribute 'logs_home'
``` 
we should capture it

**Comment by canismarko** [comment]
Not sure exactly which commit this was in, but I fixed this a while ago. Calling tomopy without arguments now produces this exception:

```
Traceback (most recent call last):
  File "/home/mwolf/miniconda3/envs/tomopy-cli/bin/tomopy", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/mwolf/src/tomopy-cli/bin/tomopy", line 181, in <module>
    main()
  File "/home/mwolf/src/tomopy-cli/bin/tomopy", line 158, in main
    args = config.parse_known_args(parser, subparser=True)
  File "/home/mwolf/src/tomopy-cli/tomopy_cli/config.py", line 597, in parse_known_args
    raise TypeError("A command is required. See ``tomopy --help`` for detailed usage.")
TypeError: A command is required. See ``tomopy --help`` for detailed usage.
```

Sounds like this can be closed?
